apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datagateway
spec:
  generators:
  - git:
      repoURL: 'https://github.com/danedmunds/argocd-config-apps'
      revision: "main"
      directories:
        - path: data-gateway/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/danedmunds/argocd-config-apps'
        targetRevision: "main"
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
