apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-server
  managedFields:
  name: argocd-server-nodeport
  namespace: argocd
spec:
  ports:
  - nodePort: 30443
    port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:qlik-trial/argocd-config-apps
      sshPrivateKeySecret:
        name: argocd-github-secret
        key: privateKey
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-secret
  namespace: argocd
type: Opaque
data:
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDbExFNkd1SXM4TEs1aERCL2lzVkJHQTRnSUdPcWpNVzMyN2NJa2lDUngyZ0FBQUpqOW94QnYvYU1RCmJ3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ2xMRTZHdUlzOExLNWhEQi9pc1ZCR0E0Z0lHT3FqTVczMjdjSWtpQ1J4MmcKQUFBRUQ2dzNKTjZtcUsydDBQWkVqYzI2MVZkcGFMS05nQmgxU3JJdG9FYnRSSG82VXNUb2E0aXp3c3JtRU1IK0t4VUVZRAppQWdZNnFNeGJmYnR3aVNJSkhIYUFBQUFEbUZ5WjI5alpDQnpjMmdnYTJWNUFRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: 1.58.20
  labels:
    app: local-volumes
    release: qliksense
  name: ca-certificates
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  claimRef:
    name: ca-certificates
    namespace: default
  local:
    path: /data/qliksense/ca-certificates
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: 1.58.20
  labels:
    app: qliksense
    release: qlik-default
  name: ca-certificates
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
  volumeName: ca-certificates