apiVersion: v2
name: data-gateway-controller
type: application
version: 0.0.6
appVersion: 0.0.6
dependencies:
- name: data-gateway-controller
  version: 0.0.6
  repository: oci://ghcr.io/qlik-download/helm
