apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fort-region-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ghcr.io/qlik-download/helm
    chart: fort-region-gateway
    targetRevision: 0.2.3
    helm:
      parameters:
      - name: configs.data.redisUri
        value: redis-master:6379
      - name: redis.enabled
        value: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true