fort-region-gateway:
  configs:
    data:
      redisUri: redis-master:6379
      enableRedisTokens: false
      featureFortOauthP1: false
      enableAccessTokens: false
      disableJwtAuth: true
      deploymentType: data-gateway
      featuresOverlay: "{}"
  iotConfig:
    provision: false
    configName: iot-config
  iotSecret:
    provision: false
    secretName: iot-secret
  ingress:
    enabled: false
    paths: []
  fortIdp:
    enabled: false
  regionRedirect:
    enabled: false
  egressServices:
    - name: forts
      port: 6080
  redis:
    enabled: false
