fort-region-gateway:
  configs:
    data:
      redisUri: redis-master:6379
      enableRedisTokens: false
      featureFortOauthP1: false
      enableAccessTokens: false
      disableJwtAuth: true
      deploymentType: data-gateway
      tenantId:
      fortTenantUrl:
      featuresOverlay:
  secrets:
    stringData:
      interactiveIdpClientId:
      interactiveIdpClientSecret:
      fortPrivateKey:
  iotConfig:
    useForeign: true
    configName: iot-config
  iotSecret:
    useForeign: true
    secretName: iot-secret
  ingress:
    enabled: false
    paths: []
  fortIdp:
    enabled: false
  regionRedirect:
    enabled: false
  egressServices:
    - name: forts
      port: 6080
  redis:
    enabled: false
  deployment:
    volumes:
      secret:
        iot-secret:
          secretName: iot-secret
    container:
      volumeMounts:
        iot-secret:
          readOnly: true
          mountPath: "/run/secrets/qlik.com/iot-secret"
