fort-region-gateway:
  image:
    registry: ghcr.io/qlik-download
  configs:
   data:
     redisUri: redis-master:6379
     enableRedisTokens: false
  ingress:
    enabled: false
    paths: []
  fortIdp:
    enabled: false
  regionRedirect:
    enabled: false
  egressServices:
    - name: forts
      port: 6080
  redis:
   enabled: false
