apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator
  namespace: default
---
apiVersion: v1
data:
  mongodbUri: bW9uZ29kYjovL2VsYXN0aWMtaW5mcmEtbW9uZ29kYjoyNzAxNy9hcHAtZXZhbHVhdG9y
  redisPassword: TkdrVXAwVkRKdGMzeGl5Qw==
  tokenAuthPrivateKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JR2tBZ0VCQkRBUU9YUHpGTVBObDNxVnlnTStwRHErdDA2SXRwTC9xaHhOd2N2SE9hd05Dem1qTytIT0dIWW8KMStheEZJMjJFRWVnQndZRks0RUVBQ0toWkFOaUFBU0RiTnROVmZBSnNSL3pra3ZDaDB0MDNrZnBRc2psRXNsMgptbE5oZ3Ayd05qS1J1Sk9oL3YvZUdHZEYzQTB5Y3pjRk51MmxhSi9xeHYySVgvLytFaDlYcUZiS1UyeUpneW9VCitON0JleGh0aGZpbllOWUdJRTF0TlZlcEF2bGhzS009Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
  tokenAuthPrivateKeyId: UnZhWm5YSVpkZklzem5YWFpzN05Ec3lzVFdxUF9GVjF2OWxQOEV3SnJwdw==
kind: Secret
metadata:
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  collectionsUri: http://collections:8080
  edgeAuthUri: http://edge-auth:8080
  featureFlagsUri: http://feature-flags:8080
  ingressAuthUrl: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
  keysUri: http://keys:8080
  licensesUri: http://licenses:9200
  mongoAddr: mongodb://mongodb:27017
  mongoAuthDB: qliksense
  mongoAuthentication: "true"
  mongoDatabase: qliksense
  mongoUsername: fort-user
  natsStreamingClusterId: messaging-nats-streaming-cluster
  natsUri: nats://messaging-nats-client:4222
  qixSessionsUri: http://qix-sessions:8080
  redisUri: redis-master:6379
kind: ConfigMap
metadata:
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator-configs
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator
  namespace: default
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-evaluator
subjects:
  - kind: ServiceAccount
    name: app-evaluator
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
    prometheus.io/scrape_high_cardinality: "true"
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator
  namespace: default
spec:
  ports:
    - name: app-evaluator
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: app-evaluator-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: app-evaluator
    release: app-evaluator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-evaluator
      release: app-evaluator
  template:
    metadata:
      annotations:
        checksum/configs: 347bc462a03f40e95211a35c739122441f1e021942f42861e1f535c0ce5dc0e1
        checksum/secrets: d4787a3c029a8a80d05f770bcb58f9b534671a9530083e3c18eefbc0b197543a
      labels:
        app: app-evaluator
        domain: analytics
        messaging-nats-client: "true"
        release: app-evaluator
    spec:
      containers:
        - env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TOKEN_AUTH_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/app-evaluator/tokenAuthPrivateKey
            - name: TOKEN_AUTH_PRIVATE_KEY_ID_FILE
              value: /run/secrets/qlik.com/app-evaluator/tokenAuthPrivateKeyId
            - name: COLLECTIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: collectionsUri
                  name: app-evaluator-configs
            - name: EDGE_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: edgeAuthUri
                  name: app-evaluator-configs
            - name: FEATURE_FLAGS_URI
              valueFrom:
                configMapKeyRef:
                  key: featureFlagsUri
                  name: app-evaluator-configs
            - name: INGRESS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: ingressAuthUrl
                  name: app-evaluator-configs
            - name: KEYS_URI
              valueFrom:
                configMapKeyRef:
                  key: keysUri
                  name: app-evaluator-configs
            - name: LICENSES_URI
              valueFrom:
                configMapKeyRef:
                  key: licensesUri
                  name: app-evaluator-configs
            - name: MONGO_ADDR
              valueFrom:
                configMapKeyRef:
                  key: mongoAddr
                  name: app-evaluator-configs
            - name: MONGO_AUTH_DB
              valueFrom:
                configMapKeyRef:
                  key: mongoAuthDB
                  name: app-evaluator-configs
            - name: MONGO_AUTHENTICATION
              valueFrom:
                configMapKeyRef:
                  key: mongoAuthentication
                  name: app-evaluator-configs
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: mongoDatabase
                  name: app-evaluator-configs
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: mongoUsername
                  name: app-evaluator-configs
            - name: NATS_STREAMING_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: natsStreamingClusterId
                  name: app-evaluator-configs
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  key: natsUri
                  name: app-evaluator-configs
            - name: QIX_SESSIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: qixSessionsUri
                  name: app-evaluator-configs
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: app-evaluator-configs
            - name: DISABLE_OTLP
              value: "true"
            - name: JAEGER_DISABLED
              value: "true"
            - name: AUTH_ENABLED
              value: "true"
            - name: AUTH_JWT_AUD
              value: qlik.api.internal
            - name: AUTH_JWT_ISS
              value: qlik.api.internal
            - name: ENGINE_METRICS_PORT
              value: "9090"
            - name: MAX_PARALLEL_CONSUMERS
              value: "5"
            - name: MONGO_ENABLED
              value: ""
            - name: NATS_ENABLED
              value: ""
            - name: NATS_TOKEN_AUTH_ENABLED
              value: "true"
            - name: QIX_SESSIONS_ENABLED
              value: ""
            - name: REDIS_ENABLED
              value: ""
            - name: STAN_SYSTEM_EVENTS_SUBJECT
              value: system-events.evaluations
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: "1810"
            - name: TOKEN_AUTH_ENABLED
              value: "true"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/app-evaluator:1.8.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          name: app-evaluator
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/app-evaluator
              name: app-evaluator-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      serviceAccountName: app-evaluator
      terminationGracePeriodSeconds: 1810
      volumes:
        - name: app-evaluator-secrets
          secret:
            secretName: app-evaluator-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/(.*) /$1 break;
    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: app-evaluator
    app.kubernetes.io/component: app-evaluator
    app.kubernetes.io/instance: app-evaluator
    app.kubernetes.io/name: app-evaluator
    app.kubernetes.io/version: 1.8.2
    chart: app-evaluator-1.8.2
    domain: analytics
    heritage: Helm
    release: app-evaluator
  name: app-evaluator
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-evaluator
                port:
                  number: 8080
            path: /api/v1/apps/(.+)/evaluations
            pathType: ImplementationSpecific
          - backend:
              service:
                name: app-evaluator
                port:
                  number: 8080
            path: /api/v1/apps/evaluations
            pathType: ImplementationSpecific
          - backend:
              service:
                name: app-evaluator
                port:
                  number: 8080
            path: /api/v1/evaluations
            pathType: ImplementationSpecific
