apiVersion: v1
kind: Secret
metadata:
  labels:
    app: data-connector-jdbc
    app.kubernetes.io/component: data-connector-jdbc
    app.kubernetes.io/instance: data-connector-jdbc
    app.kubernetes.io/name: data-connector-jdbc
    app.kubernetes.io/version: 0.97.0
    chart: data-connector-jdbc-0.97.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-jdbc
  name: data-connector-jdbc-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  connectorCommandquerytimeout: "30"
  grpcServerPort: "50060"
  jdbcLogintimeout: "30"
  jdbcNetworktimeout: "30"
  logLevel: info
kind: ConfigMap
metadata:
  labels:
    app: data-connector-jdbc
    app.kubernetes.io/component: data-connector-jdbc
    app.kubernetes.io/instance: data-connector-jdbc
    app.kubernetes.io/name: data-connector-jdbc
    app.kubernetes.io/version: 0.97.0
    chart: data-connector-jdbc-0.97.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-jdbc
  name: data-connector-jdbc-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: command
    app: data-connector-jdbc
    app.kubernetes.io/component: data-connector-jdbc
    app.kubernetes.io/instance: data-connector-jdbc
    app.kubernetes.io/name: data-connector-jdbc
    app.kubernetes.io/version: 0.97.0
    chart: data-connector-jdbc-0.97.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-jdbc
  name: data-connector-jdbc-cmd
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: command
    app: data-connector-jdbc
    release: data-connector-jdbc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: reload
    app: data-connector-jdbc
    app.kubernetes.io/component: data-connector-jdbc
    app.kubernetes.io/instance: data-connector-jdbc
    app.kubernetes.io/name: data-connector-jdbc
    app.kubernetes.io/version: 0.97.0
    chart: data-connector-jdbc-0.97.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-jdbc
  name: data-connector-jdbc-rld
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: reload
    app: data-connector-jdbc
    release: data-connector-jdbc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: command
    app: data-connector-jdbc
    app.kubernetes.io/component: data-connector-jdbc
    app.kubernetes.io/instance: data-connector-jdbc
    app.kubernetes.io/name: data-connector-jdbc
    app.kubernetes.io/version: 0.97.0
    chart: data-connector-jdbc-0.97.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-jdbc
  name: data-connector-jdbc-cmd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: command
      app: data-connector-jdbc
      release: data-connector-jdbc
  template:
    metadata:
      annotations:
        checksum/configs: fc54b85c35bd5958cb210642476149fcca663bc6b5129b2e493b6be6756aedba
        checksum/secrets: 8755a63af4a9f6c30f79e4b1f9c2057580bbeac38ebd46247bbfe4a16051c2a6
      labels:
        action: command
        app: data-connector-jdbc
        domain: data-connectors
        release: data-connector-jdbc
    spec:
      containers:
        - env:
            - name: CONNECTOR_COMMANDQUERYTIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: connectorCommandquerytimeout
                  name: data-connector-jdbc-configs
            - name: GRPC_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: grpcServerPort
                  name: data-connector-jdbc-configs
            - name: JDBC_LOGINTIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: jdbcLogintimeout
                  name: data-connector-jdbc-configs
            - name: JDBC_NETWORKTIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: jdbcNetworktimeout
                  name: data-connector-jdbc-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-jdbc-configs
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-jdbc:0.97.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /info
              port: http
          name: data-connector-jdbc
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-jdbc-secrets
          secret:
            secretName: data-connector-jdbc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: reload
    app: data-connector-jdbc
    app.kubernetes.io/component: data-connector-jdbc
    app.kubernetes.io/instance: data-connector-jdbc
    app.kubernetes.io/name: data-connector-jdbc
    app.kubernetes.io/version: 0.97.0
    chart: data-connector-jdbc-0.97.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-jdbc
  name: data-connector-jdbc-rld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: reload
      app: data-connector-jdbc
      release: data-connector-jdbc
  template:
    metadata:
      annotations:
        checksum/configs: fc54b85c35bd5958cb210642476149fcca663bc6b5129b2e493b6be6756aedba
        checksum/secrets: 8755a63af4a9f6c30f79e4b1f9c2057580bbeac38ebd46247bbfe4a16051c2a6
      labels:
        action: reload
        app: data-connector-jdbc
        domain: data-connectors
        release: data-connector-jdbc
    spec:
      containers:
        - env:
            - name: CONNECTOR_COMMANDQUERYTIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: connectorCommandquerytimeout
                  name: data-connector-jdbc-configs
            - name: GRPC_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: grpcServerPort
                  name: data-connector-jdbc-configs
            - name: JDBC_LOGINTIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: jdbcLogintimeout
                  name: data-connector-jdbc-configs
            - name: JDBC_NETWORKTIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: jdbcNetworktimeout
                  name: data-connector-jdbc-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-jdbc-configs
            - name: CONNECTOR_BLOCKING_READ_WRITE
              value: "false"
            - name: CONNECTOR_DATALOADQUERYTIMEOUT
              value: "300"
            - name: CONNECTOR_MAX_DATA_CHUNK_SIZE
              value: "0"
            - name: GRPC_SERVER_SHUTDOWNTIMEOUT
              value: "30"
            - name: JDBC_FETCH_SIZE
              value: "1000"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-jdbc:0.97.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /info
              port: http
          name: data-connector-jdbc
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-jdbc-secrets
          secret:
            secretName: data-connector-jdbc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
