apiVersion: v1
data:
  redisPassword: TkdrVXAwVkRKdGMzeGl5Qw==
kind: Secret
metadata:
  labels:
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  commandSessionLife: "60"
  config: /opt/runner/Odbc_dotnetcore.json
  dataHost: 0.0.0.0
  dataPortRangeEnd: "50060"
  dataPortRangeStart: "50060"
  destroySessionCancel: mssql
  logLevel: INFO
  qsEnvironment: QSEOK
  redisUri: redis-master:6379
  reloadSessionLife: "20"
  reuseCommandSession: "false"
  reuseReloadSession: "false"
  serviceMode: "true"
  standalone: "false"
kind: ConfigMap
metadata:
  labels:
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: command
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc-cmd
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: http-web
      port: 6384
      protocol: TCP
      targetPort: 6384
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: command
    app: data-connector-odbc
    release: data-connector-odbc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: reload
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc-rld
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: reload
    app: data-connector-odbc
    release: data-connector-odbc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: command
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc-cmd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: command
      app: data-connector-odbc
      release: data-connector-odbc
  template:
    metadata:
      annotations:
        checksum/configs: 13f652429724c2b2a9c7c3662da1d154e4822e0953fc815d428441ac51613537
        checksum/secrets: 4128eaad3e6a5255bd32be1b204cdc78c8e73fe02f07371e39f406fc6156f1ea
      labels:
        action: command
        app: data-connector-odbc
        domain: data-connectors
        release: data-connector-odbc
    spec:
      containers:
        - env:
            - name: COMMAND_SESSION_LIFE
              valueFrom:
                configMapKeyRef:
                  key: commandSessionLife
                  name: data-connector-odbc-configs
            - name: CONFIG
              valueFrom:
                configMapKeyRef:
                  key: config
                  name: data-connector-odbc-configs
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  key: dataHost
                  name: data-connector-odbc-configs
            - name: DATA_PORT_RANGE_END
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeEnd
                  name: data-connector-odbc-configs
            - name: DATA_PORT_RANGE_START
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeStart
                  name: data-connector-odbc-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-odbc-configs
            - name: QS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: qsEnvironment
                  name: data-connector-odbc-configs
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: data-connector-odbc-configs
            - name: REUSE_COMMAND_SESSION
              valueFrom:
                configMapKeyRef:
                  key: reuseCommandSession
                  name: data-connector-odbc-configs
            - name: SERVICE_MODE
              valueFrom:
                configMapKeyRef:
                  key: serviceMode
                  name: data-connector-odbc-configs
            - name: STANDALONE
              valueFrom:
                configMapKeyRef:
                  key: standalone
                  name: data-connector-odbc-configs
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-odbc:6.197.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-odbc
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/data-connector-odbc
              name: data-connector-odbc-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-odbc-secrets
          secret:
            secretName: data-connector-odbc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: reload
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc-rld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: reload
      app: data-connector-odbc
      release: data-connector-odbc
  template:
    metadata:
      annotations:
        checksum/configs: ef86d239cd60adc34353bf1337dc189402c730cfb0c80b9d8b995a4fa3365398
        checksum/secrets: 4128eaad3e6a5255bd32be1b204cdc78c8e73fe02f07371e39f406fc6156f1ea
      labels:
        action: reload
        app: data-connector-odbc
        domain: data-connectors
        release: data-connector-odbc
    spec:
      containers:
        - env:
            - name: CONFIG
              valueFrom:
                configMapKeyRef:
                  key: config
                  name: data-connector-odbc-configs
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  key: dataHost
                  name: data-connector-odbc-configs
            - name: DATA_PORT_RANGE_END
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeEnd
                  name: data-connector-odbc-configs
            - name: DATA_PORT_RANGE_START
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeStart
                  name: data-connector-odbc-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-odbc-configs
            - name: QS_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: qsEnvironment
                  name: data-connector-odbc-configs
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: data-connector-odbc-configs
            - name: RELOAD_SESSION_LIFE
              valueFrom:
                configMapKeyRef:
                  key: reloadSessionLife
                  name: data-connector-odbc-configs
            - name: REUSE_RELOAD_SESSION
              valueFrom:
                configMapKeyRef:
                  key: reuseReloadSession
                  name: data-connector-odbc-configs
            - name: SERVICE_MODE
              valueFrom:
                configMapKeyRef:
                  key: serviceMode
                  name: data-connector-odbc-configs
            - name: STANDALONE
              valueFrom:
                configMapKeyRef:
                  key: standalone
                  name: data-connector-odbc-configs
            - name: DISABLE_BULK_READER
              value: "false"
            - name: ENABLE_SHUTDOWN_DRAIN
              value: "false"
            - name: FORCE_BULK_READER
              value: "false"
            - name: MAX_ACTIVE_RELOADS
              value: "3"
            - name: RELOADS_ABOVE_MAX_ALLOWANCE
              value: "2"
            - name: SHUTDOWN_TIMEOUT
              value: "30"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-odbc:6.197.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-odbc
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/data-connector-odbc
              name: data-connector-odbc-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-connector-odbc-secrets
          secret:
            secretName: data-connector-odbc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/login?returnto=$escaped_request_uri
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
  labels:
    app: data-connector-odbc
    app.kubernetes.io/component: data-connector-odbc
    app.kubernetes.io/instance: data-connector-odbc
    app.kubernetes.io/name: data-connector-odbc
    app.kubernetes.io/version: 6.197.0
    chart: data-connector-odbc-6.197.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-odbc
  name: data-connector-odbc
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: data-connector-odbc-cmd
                port:
                  number: 6384
            path: /customdata/64/(QvOdbcConnectorPackage)/(.+)
            pathType: ImplementationSpecific
