apiVersion: v1
data:
  mongodbUri: bW9uZ29kYjovL2VsYXN0aWMtaW5mcmEtbW9uZ29kYjoyNzAxNy9kYXRhLXByZXA/c3NsPWZhbHNl
  redisPassword: TkdrVXAwVkRKdGMzeGl5Qw==
  tokenAuthPrivateKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JR2tBZ0VCQkRCMFBqWDhkNmZxYjd1TENkdFVhSzhtandVdy93TEhVSEMzcUo2bXJIVXJhQ21LUzZaWEtET1UKbEZuekgvU2V2NGlnQndZRks0RUVBQ0toWkFOaUFBUmk3NUpDdHJ0QnN2MWdKcGgzbGR3cW5BR1YvVXJ4UjQ1TgpIOTRZMjk5eTZYM3pPNTZTeHlsbU12b3VKYlhDWk5ma1hGVnpDUnY5SHJqcjVqdzBTQ1dkTDIyYXZZeUpmRzZhCnJHZUdwZ0l3UDVoM0N6YWdoQ1U1ajZHK3JkdWpsaTQ9Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
  tokenAuthPrivateKeyId: d2NWY0RfbkR3dy1mT3dMTjVUc3RNejBoU1pVQmJ5NG14NzdJY2FjYVExVQ==
kind: Secret
metadata:
  labels:
    app: data-prep
    app.kubernetes.io/component: data-prep
    app.kubernetes.io/instance: data-prep
    app.kubernetes.io/name: data-prep
    app.kubernetes.io/version: 3.434.0
    chart: data-prep-3.434.0
    heritage: Helm
    release: data-prep
  name: data-prep-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  dataConnectionsUri: http://data-connections:9011
  edgeAuthUri: http://edge-auth:8080
  featureFlagsUri: http://feature-flags:8080
  ingressAuthUrl: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
  keysUri: http://keys:8080
  logLevel: verbose
  precedentsUri: http://precedents:9054
  qixDataFilesUri: http://qix-datafiles:8080
  qixSessionsUri: http://qix-sessions:8080
  redisUri: redis://redis-master:6379
  spacesUri: http://spaces:6080
kind: ConfigMap
metadata:
  labels:
    app: data-prep
    app.kubernetes.io/component: data-prep
    app.kubernetes.io/instance: data-prep
    app.kubernetes.io/name: data-prep
    app.kubernetes.io/version: 3.434.0
    chart: data-prep-3.434.0
    heritage: Helm
    release: data-prep
  name: data-prep-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9072"
    prometheus.io/scrape: "true"
  labels:
    app: data-prep
    app.kubernetes.io/component: data-prep
    app.kubernetes.io/instance: data-prep
    app.kubernetes.io/name: data-prep
    app.kubernetes.io/version: 3.434.0
    chart: data-prep-3.434.0
    heritage: Helm
    release: data-prep
  name: data-prep
  namespace: default
spec:
  ports:
    - name: data-prep
      port: 9072
      protocol: TCP
      targetPort: 9072
  selector:
    app: data-prep
    release: data-prep
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-prep
    app.kubernetes.io/component: data-prep
    app.kubernetes.io/instance: data-prep
    app.kubernetes.io/name: data-prep
    app.kubernetes.io/version: 3.434.0
    chart: data-prep-3.434.0
    heritage: Helm
    release: data-prep
  name: data-prep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prep
      release: data-prep
  template:
    metadata:
      annotations:
        checksum/configs: 811840ccb65b4164e3d99fdca5b7ca72d87c6e613805cecd9c67163e0710e199
        checksum/secrets: a02e04f8ec522d20df5ee51e2a5802731543816e76c2b83c96cddea286edab73
      labels:
        app: data-prep
        release: data-prep
    spec:
      containers:
        - env:
            - name: TOKEN_AUTH_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/data-prep/tokenAuthPrivateKey
            - name: TOKEN_AUTH_PRIVATE_KEY_ID_FILE
              value: /run/secrets/qlik.com/data-prep/tokenAuthPrivateKeyId
            - name: DATA_CONNECTIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: dataConnectionsUri
                  name: data-prep-configs
            - name: EDGE_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: edgeAuthUri
                  name: data-prep-configs
            - name: FEATURE_FLAGS_URI
              valueFrom:
                configMapKeyRef:
                  key: featureFlagsUri
                  name: data-prep-configs
            - name: INGRESS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: ingressAuthUrl
                  name: data-prep-configs
            - name: KEYS_URI
              valueFrom:
                configMapKeyRef:
                  key: keysUri
                  name: data-prep-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-prep-configs
            - name: PRECEDENTS_URI
              valueFrom:
                configMapKeyRef:
                  key: precedentsUri
                  name: data-prep-configs
            - name: QIX_DATA_FILES_URI
              valueFrom:
                configMapKeyRef:
                  key: qixDataFilesUri
                  name: data-prep-configs
            - name: QIX_SESSIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: qixSessionsUri
                  name: data-prep-configs
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: data-prep-configs
            - name: SPACES_URI
              valueFrom:
                configMapKeyRef:
                  key: spacesUri
                  name: data-prep-configs
            - name: DISABLE_OTLP
              value: "true"
            - name: JAEGER_DISABLED
              value: "true"
            - name: BINDADDRESS
              value: '::'
            - name: DATAPATH
              value: /
            - name: KEEPALIVE
              value: "30000"
            - name: LOGICALAPPSFOLDER
              value: /qlik/apps
            - name: LOGICALGEOFOLDER
              value: /geo
            - name: LOGPATH
              value: /logs
            - name: MODE
              value: elastic
            - name: PORT
              value: "9072"
            - name: TTL
              value: "10000"
            - name: WORKERPOOL
              value: "true"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-prep-service:3.434.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: data-prep
          ports:
            - containerPort: 9072
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/data-prep
              name: data-prep-secrets
              readOnly: true
            - mountPath: /qlik/apps
              name: data-prep-apps-storage
              readOnly: false
            - mountPath: /Apps
              name: data-prep-apps-storage
              readOnly: false
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-prep-secrets
          secret:
            secretName: data-prep-secrets
        - emptyDir: {}
          name: data-prep-apps-storage
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/dataprepservice/(.*) /$1 break;
      rewrite (?i)/dataprepservice/(.*) /$1 break;
    nginx.ingress.kubernetes.io/cors-allow-headers: x-qlik-xrfkey,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Qlik-Web-Integration-ID,Qlik-CSRF-Token
    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: data-prep
    app.kubernetes.io/component: data-prep
    app.kubernetes.io/instance: data-prep
    app.kubernetes.io/name: data-prep
    app.kubernetes.io/version: 3.434.0
    chart: data-prep-3.434.0
    heritage: Helm
    release: data-prep
  name: data-prep
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/openapi
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/model/current
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/model/last(.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/global/analysis/descriptor
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/analysis
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/assets
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/business-model
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/vocabulary
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/associativeInsight
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/model/session/close
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-prep
                port:
                  number: 9072
            path: /api/dataprepservice/v1/apps/(.*)/influencer
            pathType: ImplementationSpecific
