apiVersion: v1
kind: Secret
metadata:
  labels:
    app: data-connector-nfs
    chart: data-connector-nfs-1.2.8
    heritage: Helm
    release: data-connector-nfs
  name: data-connector-nfs-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  keysUri: http://keys:8080/v1/keys/qlik.api.internal
  logLevel: debug
  pdsUri: http://policy-decisions:5080
  spacesUri: http://spaces:6080
  tokenAuthUri: http://edge-auth:8080/v1/internal-tokens
kind: ConfigMap
metadata:
  labels:
    app: data-connector-nfs
    chart: data-connector-nfs-1.2.8
    heritage: Helm
    release: data-connector-nfs
  name: data-connector-nfs-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: data-connector-nfs
    chart: data-connector-nfs-1.2.8
    heritage: Helm
    release: data-connector-nfs
  name: data-connector-nfs
  namespace: default
spec:
  ports:
    - name: data-connector-nfs
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: data-connector-nfs
    release: data-connector-nfs
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-connector-nfs
    chart: data-connector-nfs-1.2.8
    heritage: Helm
    release: data-connector-nfs
  name: data-connector-nfs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-connector-nfs
      release: data-connector-nfs
  template:
    metadata:
      annotations:
        checksum/configs: 4a8eeea4955333e33959774744a4449fa329e547c3b1ebadde13a38d45a58452
        checksum/secrets: 2ae0aa9aa6227bf3ff4e02219e3c5f085296d361c182e7462fd75e259968f87e
      labels:
        app: data-connector-nfs
        release: data-connector-nfs
    spec:
      containers:
        - env:
            - name: KEYS_URI
              valueFrom:
                configMapKeyRef:
                  key: keysUri
                  name: data-connector-nfs-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-nfs-configs
            - name: PDS_URI
              valueFrom:
                configMapKeyRef:
                  key: pdsUri
                  name: data-connector-nfs-configs
            - name: SPACES_URI
              valueFrom:
                configMapKeyRef:
                  key: spacesUri
                  name: data-connector-nfs-configs
            - name: TOKEN_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: tokenAuthUri
                  name: data-connector-nfs-configs
            - name: DISABLE_OTLP
              value: "true"
            - name: JAEGER_DISABLED
              value: "true"
            - name: AUTH_ENABLED
              value: "true"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-nfs:1.0.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          name: data-connector-nfs
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 50051
              name: grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          resources: null
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-nfs-secrets
          secret:
            secretName: data-connector-nfs-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/customdata/64/data-connector-nfs/(.*) /$1 break;
    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: data-connector-nfs
    chart: data-connector-nfs-1.2.8
    heritage: Helm
    release: data-connector-nfs
  name: data-connector-nfs
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: data-connector-nfs
              servicePort: 8080
            path: /customdata/64/data-connector-nfs
