apiVersion: v1
kind: Secret
metadata:
  labels:
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  dataHost: 0.0.0.0
  dataPortRangeEnd: "50060"
  dataPortRangeStart: "50060"
  grpcMaxReceiveMessageSize: "536870912"
  grpcMaxSendMessageSize: "536870912"
  licensesUri: http://licenses:9200
  logLevel: info
  shutdownTimeout: "30"
kind: ConfigMap
metadata:
  labels:
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: command
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-cmd
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: command
    app: data-connector-sap-sql
    release: data-connector-sap-sql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: reload
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-rld
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: reload
    app: data-connector-sap-sql
    release: data-connector-sap-sql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  labels:
    action: web
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-web
  namespace: default
spec:
  ports:
    - name: http
      port: 6384
      protocol: TCP
      targetPort: 6384
  selector:
    action: web
    app: data-connector-sap-sql
    release: data-connector-sap-sql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: command
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-cmd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: command
      app: data-connector-sap-sql
      release: data-connector-sap-sql
  template:
    metadata:
      annotations:
        checksum/configs: 32abfe171e31287068593e00999822567965c650d406340838cd7f65289d3609
        checksum/secrets: dbda9d9def60994a32389834b74c7db19b9df5c7c4e28e89c08f4def1f50fc43
      labels:
        action: command
        app: data-connector-sap-sql
        release: data-connector-sap-sql
    spec:
      containers:
        - env:
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  key: dataHost
                  name: data-connector-sap-sql-configs
            - name: DATA_PORT_RANGE_END
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeEnd
                  name: data-connector-sap-sql-configs
            - name: DATA_PORT_RANGE_START
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeStart
                  name: data-connector-sap-sql-configs
            - name: GRPC_MAX_RECEIVE_MESSAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: grpcMaxReceiveMessageSize
                  name: data-connector-sap-sql-configs
            - name: GRPC_MAX_SEND_MESSAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  key: grpcMaxSendMessageSize
                  name: data-connector-sap-sql-configs
            - name: LICENSES_URI
              valueFrom:
                configMapKeyRef:
                  key: licensesUri
                  name: data-connector-sap-sql-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-sap-sql-configs
            - name: CONFIG
              value: /opt/runner/SAP-sql_dotnetcore.json
            - name: SERVICE_MODE
              value: "true"
            - name: STANDALONE
              value: "false"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-sap-sql:7.3.11
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-sap-sql
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-sap-sql-secrets
          secret:
            secretName: data-connector-sap-sql-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: reload
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-rld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: reload
      app: data-connector-sap-sql
      release: data-connector-sap-sql
  template:
    metadata:
      annotations:
        checksum/configs: 94f71fc40569cdc0cff484b2d1f441a84e4a5b755ce608843160eaf28ed0d90a
        checksum/secrets: dbda9d9def60994a32389834b74c7db19b9df5c7c4e28e89c08f4def1f50fc43
      labels:
        action: reload
        app: data-connector-sap-sql
        release: data-connector-sap-sql
    spec:
      containers:
        - env:
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  key: dataHost
                  name: data-connector-sap-sql-configs
            - name: DATA_PORT_RANGE_END
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeEnd
                  name: data-connector-sap-sql-configs
            - name: DATA_PORT_RANGE_START
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeStart
                  name: data-connector-sap-sql-configs
            - name: LICENSES_URI
              valueFrom:
                configMapKeyRef:
                  key: licensesUri
                  name: data-connector-sap-sql-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: data-connector-sap-sql-configs
            - name: SHUTDOWN_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: shutdownTimeout
                  name: data-connector-sap-sql-configs
            - name: CONFIG
              value: /opt/runner/SAP-sql_dotnetcore.json
            - name: MAX_ACTIVE_RELOADS
              value: "3"
            - name: SERVICE_MODE
              value: "true"
            - name: STANDALONE
              value: "false"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-sap-sql:7.3.11
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-sap-sql
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-connector-sap-sql-secrets
          secret:
            secretName: data-connector-sap-sql-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: web
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: web
      app: data-connector-sap-sql
      release: data-connector-sap-sql
  template:
    metadata:
      annotations:
        checksum/configs: e38d65eec663029dfcbd09024b345899c9bc7f30d40edea42200705eb768c1e8
        checksum/secrets: dbda9d9def60994a32389834b74c7db19b9df5c7c4e28e89c08f4def1f50fc43
      labels:
        action: web
        app: data-connector-sap-sql
        release: data-connector-sap-sql
    spec:
      containers:
        - env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-sap-sql-web:7.3.11
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          name: data-connector-sap-sql
          ports:
            - containerPort: 6384
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-sap-sql-secrets
          secret:
            secretName: data-connector-sap-sql-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/login?returnto=$escaped_request_uri
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
  labels:
    app: data-connector-sap-sql
    app.kubernetes.io/component: data-connector-sap-sql
    app.kubernetes.io/instance: data-connector-sap-sql
    app.kubernetes.io/name: data-connector-sap-sql
    app.kubernetes.io/version: 7.3.11
    chart: data-connector-sap-sql-7.3.11
    heritage: Helm
    release: data-connector-sap-sql
  name: data-connector-sap-sql-web
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: data-connector-sap-sql-web
                port:
                  number: 6384
            path: /customdata/64/(QvSAPSqlConnector)/(.+)
            pathType: ImplementationSpecific
