apiVersion: v1
data:
  redisPassword: TkdrVXAwVkRKdGMzeGl5Qw==
kind: Secret
metadata:
  labels:
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  dataHost: 0.0.0.0
  dataPortRangeEnd: "50060"
  dataPortRangeStart: "50060"
  ingressAuthUrl: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
  qwcAllowReferenceConnector: "true"
  qwcLogLevel: INFO
  qwcProxy: ""
  redisUri: redis-master:6379
kind: ConfigMap
metadata:
  labels:
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: command
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-cmd
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: command
    app: data-connector-qwc
    release: data-connector-qwc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "3005"
    prometheus.io/scrape: "true"
  labels:
    action: reload
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-rld
  namespace: default
spec:
  ports:
    - name: http
      port: 3005
      protocol: TCP
      targetPort: 3005
    - name: grpc
      port: 50060
      protocol: TCP
      targetPort: 50060
  selector:
    action: reload
    app: data-connector-qwc
    release: data-connector-qwc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  labels:
    action: web
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-web
  namespace: default
spec:
  ports:
    - name: http
      port: 6384
      protocol: TCP
      targetPort: 6384
  selector:
    action: web
    app: data-connector-qwc
    release: data-connector-qwc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: command
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-cmd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: command
      app: data-connector-qwc
      release: data-connector-qwc
  template:
    metadata:
      annotations:
        checksum/configs: b203db048bffeb4cdbe412be4b9f4424e09bb78d738f03f53b55946131d0c5da
        checksum/secrets: b5d6857582633de66d479ffd73c85704ae305159c03a0ba388ca81bd7771cdaf
      labels:
        action: command
        app: data-connector-qwc
        domain: data-connectors
        release: data-connector-qwc
    spec:
      containers:
        - env:
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  key: dataHost
                  name: data-connector-qwc-configs
            - name: DATA_PORT_RANGE_END
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeEnd
                  name: data-connector-qwc-configs
            - name: DATA_PORT_RANGE_START
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeStart
                  name: data-connector-qwc-configs
            - name: QWC_ALLOW_REFERENCE_CONNECTOR
              valueFrom:
                configMapKeyRef:
                  key: qwcAllowReferenceConnector
                  name: data-connector-qwc-configs
            - name: QWC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: qwcLogLevel
                  name: data-connector-qwc-configs
            - name: QWC_PROXY
              valueFrom:
                configMapKeyRef:
                  key: qwcProxy
                  name: data-connector-qwc-configs
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: data-connector-qwc-configs
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-qwc:4.23.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-qwc
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/data-connector-qwc
              name: data-connector-qwc-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-qwc-secrets
          secret:
            secretName: data-connector-qwc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: reload
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-rld
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: reload
      app: data-connector-qwc
      release: data-connector-qwc
  template:
    metadata:
      annotations:
        checksum/configs: b203db048bffeb4cdbe412be4b9f4424e09bb78d738f03f53b55946131d0c5da
        checksum/secrets: b5d6857582633de66d479ffd73c85704ae305159c03a0ba388ca81bd7771cdaf
      labels:
        action: reload
        app: data-connector-qwc
        domain: data-connectors
        release: data-connector-qwc
    spec:
      containers:
        - env:
            - name: DATA_HOST
              valueFrom:
                configMapKeyRef:
                  key: dataHost
                  name: data-connector-qwc-configs
            - name: DATA_PORT_RANGE_END
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeEnd
                  name: data-connector-qwc-configs
            - name: DATA_PORT_RANGE_START
              valueFrom:
                configMapKeyRef:
                  key: dataPortRangeStart
                  name: data-connector-qwc-configs
            - name: QWC_ALLOW_REFERENCE_CONNECTOR
              valueFrom:
                configMapKeyRef:
                  key: qwcAllowReferenceConnector
                  name: data-connector-qwc-configs
            - name: QWC_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: qwcLogLevel
                  name: data-connector-qwc-configs
            - name: QWC_PROXY
              valueFrom:
                configMapKeyRef:
                  key: qwcProxy
                  name: data-connector-qwc-configs
            - name: REDIS_URI
              valueFrom:
                configMapKeyRef:
                  key: redisUri
                  name: data-connector-qwc-configs
            - name: ENABLE_SHUTDOWN_DRAIN
              value: "false"
            - name: FILE_TRANSFER_ABOVE_MAX_ALLOWANCE
              value: "2"
            - name: MAX_ACTIVE_RELOADS
              value: "3"
            - name: SHUTDOWN_TIMEOUT
              value: "30"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-qwc:4.23.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-qwc
          ports:
            - containerPort: 3005
              name: http
              protocol: TCP
            - containerPort: 50060
              name: grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/data-connector-qwc
              name: data-connector-qwc-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-connector-qwc-secrets
          secret:
            secretName: data-connector-qwc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    action: web
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      action: web
      app: data-connector-qwc
      release: data-connector-qwc
  template:
    metadata:
      annotations:
        checksum/configs: 86b4d7b2b006a2bdfa7739fd814ba18797c68fd72727e0c9867c8fcd29e5ba2b
        checksum/secrets: b5d6857582633de66d479ffd73c85704ae305159c03a0ba388ca81bd7771cdaf
      labels:
        action: web
        app: data-connector-qwc
        domain: data-connectors
        release: data-connector-qwc
    spec:
      containers:
        - env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/data-connector-qwc-web:4.23.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: data-connector-qwc
          ports:
            - containerPort: 6384
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: data-connector-qwc-secrets
          secret:
            secretName: data-connector-qwc-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/login?returnto=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2
  labels:
    app: data-connector-qwc
    app.kubernetes.io/component: data-connector-qwc
    app.kubernetes.io/instance: data-connector-qwc
    app.kubernetes.io/name: data-connector-qwc
    app.kubernetes.io/version: 4.23.0
    chart: data-connector-qwc-4.23.0
    domain: data-connectors
    heritage: Helm
    release: data-connector-qwc
  name: data-connector-qwc-web
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: data-connector-qwc-web
                port:
                  number: 6384
            path: /customdata/64/(QvWebConnectorPackage)/(.+)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: data-connector-qwc-web
                port:
                  number: 6384
            path: /customdata/64/(QvWebStorageProviderConnectorPackage)/(.+)
            pathType: ImplementationSpecific
