apiVersion: v1
kind: ServiceAccount
metadata:
  name: fort-cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fort-cert-manager
rules:
  - apiGroups:
      - ""
    resourceNames:
      - fort-cert-manager-tls-secret
    resources:
      - secrets
    verbs:
      - get
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fort-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fort-cert-manager
subjects:
  - kind: ServiceAccount
    name: fort-cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: fort-cert-manager-http
spec:
  ports:
    - name: fort-cert-manager-http
      port: 16080
      protocol: TCP
      targetPort: 16080
  selector:
    app: fort-cert-manager
  type: ClusterIP
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fort-cert-manager-cronjob
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: fort-cert-manager
        spec:
          containers:
            - env:
                - name: HTTP_PROXY
                  valueFrom:
                    configMapKeyRef:
                      key: httpProxy
                      name: qliksense-configs
                - name: HTTPS_PROXY
                  valueFrom:
                    configMapKeyRef:
                      key: httpsProxy
                      name: qliksense-configs
                - name: NO_PROXY
                  valueFrom:
                    configMapKeyRef:
                      key: noProxy
                      name: qliksense-configs
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      key: mongodbUri
                      name: qliksense-secrets
                - name: MONGODB_URI_FILE
                  value: /run/secrets/qlik.com/qliksense/mongodbUri
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: redisPassword
                      name: qliksense-secrets
                - name: REDIS_PASSWORD_FILE
                  value: /run/secrets/qlik.com/qliksense/redisPassword
              envFrom:
                - secretRef:
                    name: fort-cert-manager-secrets
                - configMapRef:
                    name: fort-cert-manager-configs
              image: ghcr.io/qlik-trial/fort-cert-manager:1.0.3
              name: main
              volumeMounts:
                - mountPath: /etc/ssl/certs
                  name: ca-certificates
                - mountPath: /run/secrets/qlik.com/qliksense
                  name: qliksense-secrets
          imagePullSecrets:
            - name: artifactory-docker-secret
          restartPolicy: Never
          serviceAccount: fort-cert-manager
          serviceAccountName: fort-cert-manager
          volumes:
            - name: ca-certificates
              persistentVolumeClaim:
                claimName: ca-certificates
            - name: qliksense-secrets
              secret:
                secretName: qliksense-secrets
  schedule: $(FORT_CERT_MGR_CJ_SCHEDULE)
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: fort-cert-manager
  name: fort-cert-manager
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: fort-cert-manager-http
                port:
                  number: 16080
            path: /.well-known/acme-challenge
            pathType: ImplementationSpecific
