apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: PLACEHOLDER
  labels:
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  name: fort-cert-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: PLACEHOLDER
  labels:
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  name: fort-cert-manager
  namespace: default
rules:
- apiGroups:
  - ""
  resourceNames:
  - fort-cert-manager-tls-secret
  resources:
  - secrets
  verbs:
  - get
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: PLACEHOLDER
  labels:
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  name: fort-cert-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fort-cert-manager
subjects:
- kind: ServiceAccount
  name: fort-cert-manager
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: PLACEHOLDER
  labels:
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  name: fort-cert-manager-http
  namespace: default
spec:
  ports:
  - name: fort-cert-manager-http
    port: 16080
    protocol: TCP
    targetPort: 16080
  selector:
    app: fort-cert-manager
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  type: ClusterIP
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: PLACEHOLDER
  labels:
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  name: fort-cert-manager-cronjob
  namespace: default
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: fort-cert-manager
        spec:
          containers:
          - env:
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
            - name: REDIS_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: redisEncryptionKey
                  name: qliksense-secrets
            - name: REDIS_ENCRYPTION_KEY_FILE
              value: /run/secrets/qlik.com/qliksense/redisEncryptionKey
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: minioRootUser
                  name: qliksense-secrets
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: minioRootPassword
                  name: qliksense-secrets
            - name: FORT_ID
              valueFrom:
                configMapKeyRef:
                  key: fortId
                  name: qliksense-configs
            - name: FORT_IOT_CERTIFICATE_ID
              valueFrom:
                configMapKeyRef:
                  key: fortIotCertificateId
                  name: qliksense-configs
            - name: FORT_IOT_THING_NAME
              valueFrom:
                configMapKeyRef:
                  key: fortressId
                  name: qliksense-configs
            - name: FORT_NAME
              valueFrom:
                configMapKeyRef:
                  key: fortName
                  name: qliksense-configs
            - name: FORT_ORIGIN_URL
              valueFrom:
                configMapKeyRef:
                  key: fortOriginUrl
                  name: qliksense-configs
            - name: FORT_TENANT_URL
              valueFrom:
                configMapKeyRef:
                  key: fortTenantUrl
                  name: qliksense-configs
            - name: FORTRESS_IOT_THING_ROLE_ALIAS_NAME
              valueFrom:
                configMapKeyRef:
                  key: iotThingRoleAliasName
                  name: qliksense-configs
            - name: FORTRESS_ID
              valueFrom:
                configMapKeyRef:
                  key: fortressId
                  name: qliksense-configs
            - name: FORTRESS_DEVICE_CREDENTIAL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: iotCredentialUrl
                  name: qliksense-configs
            - name: FORTRESS_IOT_CREDENTIAL_ENDPOINT
              value: https://$(FORTRESS_DEVICE_CREDENTIAL_ENDPOINT)
            - name: FORTRESS_REGION
              valueFrom:
                configMapKeyRef:
                  key: iotAwsRegion
                  name: qliksense-configs
            - name: FORTRESS_THING_CA_FILE
              value: /run/secrets/qlik.com/qliksense/iotRootCa
            - name: FORTRESS_THING_CERT_FILE
              value: /run/secrets/qlik.com/qliksense/iotFortThingCert
            - name: FORTRESS_THING_DATA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: fortressThingDataEndpoint
                  name: qliksense-configs
            - name: FORTRESS_THING_KEY_FILE
              value: /run/secrets/qlik.com/qliksense/iotFortThingPrivateKey
            - name: FORTRESS_THING_NAME
              valueFrom:
                configMapKeyRef:
                  key: thingName
                  name: qliksense-configs
            - name: FORT_WEB_INTEGRATION_ID
              valueFrom:
                configMapKeyRef:
                  key: fortWebIntegrationId
                  name: qliksense-configs
            - name: FORT_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  key: tenantId
                  name: qliksense-configs
            - name: FORT_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/qliksense/iotThingPrivateKey
            - name: FORT_IOT_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/qliksense/iotThingPrivateKey
            - name: JAEGER_DISABLED
              value: "true"
            - name: DISABLE_OTLP
              value: "true"
            envFrom:
            - secretRef:
                name: fort-cert-manager-secrets
            - configMapRef:
                name: fort-cert-manager-configs
            image: ghcr.io/qlik-trial/fort-cert-manager:1.0.3
            name: main
            volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
              readOnly: true
          imagePullSecrets:
          - name: artifactory-docker-secret
          restartPolicy: Never
          serviceAccount: fort-cert-manager
          serviceAccountName: fort-cert-manager
          volumes:
          - name: ca-certificates
            persistentVolumeClaim:
              claimName: ca-certificates
          - name: qliksense-secrets
            secret:
              secretName: qliksense-secrets
  schedule: $(FORT_CERT_MGR_CJ_SCHEDULE)
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.kubernetes.io/instance: qliksense
    app.kubernetes.io/managed-by: qliksense-operator
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/version: PLACEHOLDER
  labels:
    app: fort-cert-manager
    app.kubernetes.io/name: qliksense
    app.kubernetes.io/part-of: qliksense
    release: qlik-default
  name: fort-cert-manager
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: fort-cert-manager-http
            port:
              number: 16080
        path: /.well-known/acme-challenge
        pathType: ImplementationSpecific
