apiVersion: v1
data:
  stan.conf: |
    streaming {
     cluster {
       raft_heartbeat_timeout: "6s"
       raft_election_timeout: "6s"
       raft_lease_timeout: "3s"
      }
    }
kind: ConfigMap
metadata:
  name: stan-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-streaming-nats-streaming
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "7777"
    prometheus.io/scrape: "true"
  labels:
    app: nats-streaming
    chart: nats-streaming-3.0.6
    heritage: Helm
    release: nats-streaming
  name: nats-streaming-nats-streaming-monitoring
spec:
  ports:
    - name: monitoring
      port: 8222
      targetPort: monitoring
  selector:
    app: nats-streaming
    release: nats-streaming
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nats-streaming
    chart: nats-streaming-3.0.6
    heritage: Helm
    release: nats-streaming
  name: nats-streaming-nats-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
      release: nats-streaming
  serviceName: ""
  template:
    metadata:
      annotations: null
      labels:
        app: nats-streaming
        chart: nats-streaming-3.0.6
        release: nats-streaming
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: nats-streaming
                    release: nats-streaming
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - args:
            - -cid
            - nats-streaming-nats-streaming-cluster
            - -m
            - "8222"
            - -ns
            - nats://nats-streaming-nats-client:4222
            - -mc
            - "100"
            - -msu
            - "1000"
            - -mm
            - "1000000"
            - -mb
            - 900mb
            - -ma
            - 2h
            - -hbi
            - 10s
            - -hbt
            - 10s
            - -hbf
            - "5"
            - --store
            - file
            - --dir
            - /nats/nats-streaming-nats-streaming-cluster/nats-streaming-nats-streaming-0/data
            - --file_compact_enabled
            - --file_compact_frag
            - "50"
            - --file_compact_interval
            - "300"
            - --file_compact_min_size
            - "1048576"
            - --file_buffer_size
            - "2097152"
            - --file_crc
            - --file_crc_poly
            - "3988292384"
            - --file_sync
            - --file_slice_max_msgs
            - "0"
            - --file_slice_max_bytes
            - "67108931"
            - --file_slice_max_age
            - "0"
            - --file_fds_limit
            - "0"
            - --file_parallel_recovery
            - "1"
            - --user
            - $(USER)
            - --pass
            - $(PASSWORD)
            - -SD
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: USER
              valueFrom:
                secretKeyRef:
                  key: natsClientUser
                  name: messaging-nats-secrets
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: natsClientPassword
                  name: messaging-nats-secrets
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/nats-streaming:3.0.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: monitoring
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: nats-streaming
          ports:
            - containerPort: 8222
              name: monitoring
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: monitoring
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          volumeMounts:
            - mountPath: /etc/stan-config
              name: config-volume
            - mountPath: /nats
              name: datadir
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - configMap:
            name: stan-config
          name: config-volume
        - name: datadir
          persistentVolumeClaim:
            claimName: nats-streaming-nats-streaming
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
  updateStrategy:
    type: RollingUpdate
