apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag
  namespace: default
---
apiVersion: v1
data:
  mongodbUri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvb2RhZw==
  tokenAuthPrivateKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JR2tBZ0VCQkREdnNQT0RneFFnOGNseGRxbHZQc0lid3ZOdUJhQ0dia2FQamFmVTRJd1ZzVzNyNWZ5NExzRUkKZksxWXdwWGFoMEtnQndZRks0RUVBQ0toWkFOaUFBUzVvVEpqT09oRXBpcUVzN0NYQlk1ZEhnb09UckF3Q1dHVQo0RnZPTFFkbGw2N2JtTk9HL1ZYZTRSMWVFZ1VmenQ1MlNoVXJmN01VRGNFNWdNY0NuYmIvV2g2UEJSR05SSGtHCmtkc0M1ZWhUdkFhdW8rTnlIdyt4M3VDa1hsWWZ4YzQ9Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
  tokenAuthPrivateKeyId: Si1RQzYyYUJESnJrYkpYeEVpWml4WTF3bFB3QWpKRGVaSElnRV9Eam5Ydw==
kind: Secret
metadata:
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  collectionsUri: http://collections:8080
  edgeAuthUri: http://edge-auth:8080
  encryptionUri: http://encryption:8080
  engineUri: http://engine:9076
  featureFlagsUri: http://feature-flags:8080
  ingressAuthUrl: http://edge-auth.$(NAMEPSPACE).svc.cluster.local:8080/v1/auth
  keysUri: http://keys:8080
  logLevel: info
  natsStreamingClusterId: messaging-nats-streaming-cluster
  natsUri: nats://messaging-nats-client:4222
  qixSessionsUri: http://qix-sessions:8080
  spacesUri: http://odag-spaces:6080
  usersUri: http://identities:8080
kind: ConfigMap
metadata:
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag-configs
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odag
subjects:
  - kind: ServiceAccount
    name: odag
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9098"
    prometheus.io/scrape: "true"
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag
  namespace: default
spec:
  ports:
    - name: odag
      port: 9098
      protocol: TCP
      targetPort: 9098
  selector:
    app: odag
    release: odag
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odag
      release: odag
  template:
    metadata:
      annotations:
        checksum/configs: adb202487099e94ece8d3c3d31f9099ce29dd607fbab56d602ab71707c3c63b9
        checksum/secrets: 00910264723d00bbc4c0493f2196f7d3745debfeec9f6a121fcf77484cfb72c2
      labels:
        app: odag
        messaging-nats-client: "true"
        release: odag
    spec:
      containers:
        - env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TOKEN_AUTH_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/odag/tokenAuthPrivateKey
            - name: TOKEN_AUTH_PRIVATE_KEY_ID_FILE
              value: /run/secrets/qlik.com/odag/tokenAuthPrivateKeyId
            - name: COLLECTIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: collectionsUri
                  name: odag-configs
            - name: EDGE_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: edgeAuthUri
                  name: odag-configs
            - name: ENCRYPTION_URI
              valueFrom:
                configMapKeyRef:
                  key: encryptionUri
                  name: odag-configs
            - name: ENGINE_URI
              valueFrom:
                configMapKeyRef:
                  key: engineUri
                  name: odag-configs
            - name: FEATURE_FLAGS_URI
              valueFrom:
                configMapKeyRef:
                  key: featureFlagsUri
                  name: odag-configs
            - name: INGRESS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: ingressAuthUrl
                  name: odag-configs
            - name: KEYS_URI
              valueFrom:
                configMapKeyRef:
                  key: keysUri
                  name: odag-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: odag-configs
            - name: NATS_STREAMING_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: natsStreamingClusterId
                  name: odag-configs
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  key: natsUri
                  name: odag-configs
            - name: QIX_SESSIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: qixSessionsUri
                  name: odag-configs
            - name: SPACES_URI
              valueFrom:
                configMapKeyRef:
                  key: spacesUri
                  name: odag-configs
            - name: USERS_URI
              valueFrom:
                configMapKeyRef:
                  key: usersUri
                  name: odag-configs
            - name: DISABLE_OTLP
              value: "true"
            - name: JAEGER_DISABLED
              value: "true"
            - name: AUTH_ENABLED
              value: "true"
            - name: NATS_ENABLED
              value: "true"
            - name: RELOAD_WORKLOAD_TYPE
              value: odag
            - name: TOKEN_AUTH_ENABLED
              value: "true"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/odag:2.31.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 9098
          name: odag
          ports:
            - containerPort: 9098
          readinessProbe:
            httpGet:
              path: /ready
              port: 9098
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/odag
              name: odag-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
        - args:
            - --election=odag
            - --election-namespace=default
            - --http=0.0.0.0:4040
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PORT
              value: "4040"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/leader-elector:1.12.7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 4040
          name: election
          ports:
            - containerPort: 4040
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      serviceAccountName: odag
      volumes:
        - name: odag-secrets
          secret:
            secretName: odag-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.$(NAMEPSPACE).svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/odag/(.*) /$1 break;
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Qlik-Web-Integration-ID,Qlik-CSRF-Token,X-Qlik-ServerNodeId,X-Qlik-XrfKey
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: odag
                port:
                  number: 9098
            path: /api/odag/openapi
            pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.$(NAMEPSPACE).svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/v1/(.*) /v1/$1 break;
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Qlik-Web-Integration-ID,Qlik-CSRF-Token,X-Qlik-ServerNodeId,X-Qlik-XrfKey
    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: odag
    app.kubernetes.io/component: odag
    app.kubernetes.io/instance: odag
    app.kubernetes.io/name: odag
    app.kubernetes.io/version: 2.31.0
    chart: odag-2.31.0
    heritage: Helm
    release: odag
  name: odag-api
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: odag
                port:
                  number: 9098
            path: /api/v1/odag
            pathType: ImplementationSpecific
          - backend:
              service:
                name: odag
                port:
                  number: 9098
            path: /api/v1/odaglinks
            pathType: ImplementationSpecific
          - backend:
              service:
                name: odag
                port:
                  number: 9098
            path: /api/v1/odagisavailable
            pathType: ImplementationSpecific
          - backend:
              service:
                name: odag
                port:
                  number: 9098
            path: /api/v1/odagsettings
            pathType: ImplementationSpecific
          - backend:
              service:
                name: odag
                port:
                  number: 9098
            path: /api/v1/odagrequests
            pathType: ImplementationSpecific
