apiVersion: v1
data:
  mongodbUri: bW9uZ29kYjovL2VsYXN0aWMtaW5mcmEtbW9uZ29kYjoyNzAxNy9wcmVjZWRlbnRzP3NzbD1mYWxzZQ==
  tokenAuthPrivateKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JR2tBZ0VCQkRBVmZLWkJNa3NLRW1sSDYzQkdqV0NGMktUOGM2c3ZqZWxPS0JLdGE4K2RIZlB5SEY4a1ZLbmIKWTdEeW9kdU5xYUtnQndZRks0RUVBQ0toWkFOaUFBUUpBVWVSVWdySFdtZExnR3dUa0NEQiszdFdKeGV0MFQwOQpKaDY4R2RHNjRYL2diZ0RYdERTVmx0VVo2Sjk4TDFqN1djNCtSQ3VObHkwOXNqcmNwN0wrcEZRNGxXRFdBNDloCmE5N0UwT01UOUxCYmRIdFlXVHhyN244NHpnNTd3T3M9Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
  tokenAuthPrivateKeyId: R3J2YkJsSElYRkJCN3ZycG9PbDRWeXJHSVlsXzFrVWdLU2ZOcUJvaDBkcw==
kind: Secret
metadata:
  labels:
    app: precedents
    app.kubernetes.io/component: precedents
    app.kubernetes.io/instance: precedents
    app.kubernetes.io/name: precedents
    app.kubernetes.io/version: 3.24.0
    chart: precedents-3.24.0
    heritage: Helm
    release: precedents
  name: precedents-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  edgeAuthUri: http://edge-auth:8080
  featureFlagsUri: http://feature-flags:8080
  ingressAuthUrl: http://edge-auth.default.svc.cluster.local:8080/v1/auth
  keysUri: http://keys:8080
  logLevel: info
  natsStreamingClusterId: messaging-nats-streaming-cluster
  natsUri: nats://messaging-nats-client:4222
  precedentsUri: http://precedents:9054
  qixSessionsUri: http://qix-sessions:8080
  spacesUri: http://spaces:6080
kind: ConfigMap
metadata:
  labels:
    app: precedents
    app.kubernetes.io/component: precedents
    app.kubernetes.io/instance: precedents
    app.kubernetes.io/name: precedents
    app.kubernetes.io/version: 3.24.0
    chart: precedents-3.24.0
    heritage: Helm
    release: precedents
  name: precedents-configs
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9054"
    prometheus.io/scrape: "true"
  labels:
    app: precedents
    app.kubernetes.io/component: precedents
    app.kubernetes.io/instance: precedents
    app.kubernetes.io/name: precedents
    app.kubernetes.io/version: 3.24.0
    chart: precedents-3.24.0
    heritage: Helm
    release: precedents
  name: precedents
  namespace: default
spec:
  ports:
    - name: precedents
      port: 9054
      protocol: TCP
      targetPort: 9054
  selector:
    app: precedents
    release: precedents
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: precedents
    app.kubernetes.io/component: precedents
    app.kubernetes.io/instance: precedents
    app.kubernetes.io/name: precedents
    app.kubernetes.io/version: 3.24.0
    chart: precedents-3.24.0
    heritage: Helm
    release: precedents
  name: precedents
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: precedents
      release: precedents
  template:
    metadata:
      annotations:
        checksum/configs: df02615806df7eba1198105f8afde095a10dae183ba6281eff855c8bf7f679bc
        checksum/secrets: 4797cef998dc4d5171e3065ea2791bec3946feac4260d4c7c72068ac973f095e
      labels:
        app: precedents
        messaging-nats-client: "true"
        release: precedents
    spec:
      containers:
        - env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TOKEN_AUTH_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/precedents/tokenAuthPrivateKey
            - name: TOKEN_AUTH_PRIVATE_KEY_ID_FILE
              value: /run/secrets/qlik.com/precedents/tokenAuthPrivateKeyId
            - name: EDGE_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: edgeAuthUri
                  name: precedents-configs
            - name: FEATURE_FLAGS_URI
              valueFrom:
                configMapKeyRef:
                  key: featureFlagsUri
                  name: precedents-configs
            - name: INGRESS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: ingressAuthUrl
                  name: precedents-configs
            - name: KEYS_URI
              valueFrom:
                configMapKeyRef:
                  key: keysUri
                  name: precedents-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: precedents-configs
            - name: NATS_STREAMING_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: natsStreamingClusterId
                  name: precedents-configs
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  key: natsUri
                  name: precedents-configs
            - name: PRECEDENTS_URI
              valueFrom:
                configMapKeyRef:
                  key: precedentsUri
                  name: precedents-configs
            - name: QIX_SESSIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: qixSessionsUri
                  name: precedents-configs
            - name: SPACES_URI
              valueFrom:
                configMapKeyRef:
                  key: spacesUri
                  name: precedents-configs
            - name: DISABLE_OTLP
              value: "true"
            - name: JAEGER_DISABLED
              value: "true"
            - name: CAYLEY_STORE
              value: mongo
            - name: MODE
              value: elastic
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/precedents:3.24.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: precedents
          ports:
            - containerPort: 9054
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/precedents
              name: precedents-secrets
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      volumes:
        - name: precedents-secrets
          secret:
            secretName: precedents-secrets
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.default.svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/precedent/(.*) /$1 break;
    nginx.ingress.kubernetes.io/enable-cors: "true"
  labels:
    app: precedents
    app.kubernetes.io/component: precedents
    app.kubernetes.io/instance: precedents
    app.kubernetes.io/name: precedents
    app.kubernetes.io/version: 3.24.0
    chart: precedents-3.24.0
    heritage: Helm
    release: precedents
  name: precedents
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: precedents
                port:
                  number: 9054
            path: /api/precedent
            pathType: ImplementationSpecific
