apiVersion: v1
data:
  mongodbUri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcWl4LWRhdGFmaWxlcz9zc2w9ZmFsc2U=
  tokenAuthPrivateKey: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1JR2tBZ0VCQkRBeU5BZHVYbVFZK2hrcmFGTDl6M01ZcVI4WUdqQlJiYnRsZGpNWEp3SlhnWlFDOTBjOHFHV3AKODZrakdZODVtZXVnQndZRks0RUVBQ0toWkFOaUFBUmJYWk5QQmpzTHkyNW1YWDA3U2l1ZFNyckk4anp1OGtEaQpaSVhWZ3FaWUwxZThYZmI1bEdoNnV5MWJXUG9DS3pBQ21HaDdMZjNMYXo3ODBPU3UxNituNWlqTDQ0d0x3NzcxCnY2c1VRbHNGMFVwUC9ISng2bHlKTTlRSWJrZGNPbXM9Ci0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0tLS0K
  tokenAuthPrivateKeyId: enBpWi1rbFM2NWxmY3ExSzAtbzI5U2EwQUFaWVlyNE9OXzFWQ3RBYk1FQQ==
kind: Secret
metadata:
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  awss3Accesskey: minio-access-key
  awss3Enabled: "true"
  awss3Secretkey: minio-secret-key
  awss3Uri: http://minio:9000/
  edgeAuthUri: http://edge-auth:8080
  encryptionUri: http://encryption:8080
  featureFlagsCacheexpirationinseconds: "30"
  featureFlagsUri: http://feature-flags:8080
  ingressAuthUrl: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
  keysUri: http://keys:8080
  logLevel: info
  natsStreamingClusterId: messaging-nats-streaming-cluster
  natsUri: nats://messaging-nats-client:4222
  otlpAgentPort: "55680"
  policyDecisionsUri: http://policy-decisions:5080
  policyDecisionsUseaccesscontrolservice: "false"
  spacesUri: http://spaces:6080
  temporaryContentsUri: http://temporary-contents:6080
  usersUri: http://identities:8080
kind: ConfigMap
metadata:
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles-configs
  namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles
  namespace: default
spec:
  ports:
    - name: qix-datafiles
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: qix-datafiles
    release: qix-datafiles
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qix-datafiles
      release: qix-datafiles
  template:
    metadata:
      annotations:
        checksum/configs: 479065f269e887d1f1fc71f2341cea36f472ef1af8e9b24e0d04c358af23ec7a
        checksum/secrets: 207c7fe086be37fcf3f435927e7b2345b78b08b1930ba82acfbf0716a337cdbf
      labels:
        app: qix-datafiles
        domain: data-connectors
        messaging-nats-client: "true"
        release: qix-datafiles
    spec:
      containers:
        - env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TOKEN_AUTH_PRIVATE_KEY_FILE
              value: /run/secrets/qlik.com/qix-datafiles/tokenAuthPrivateKey
            - name: TOKEN_AUTH_PRIVATE_KEY_ID_FILE
              value: /run/secrets/qlik.com/qix-datafiles/tokenAuthPrivateKeyId
            - name: AWSS3_ACCESSKEY
              valueFrom:
                configMapKeyRef:
                  key: awss3Accesskey
                  name: qix-datafiles-configs
            - name: AWSS3_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: awss3Enabled
                  name: qix-datafiles-configs
            - name: AWSS3_SECRETKEY
              valueFrom:
                configMapKeyRef:
                  key: awss3Secretkey
                  name: qix-datafiles-configs
            - name: AWSS3_URI
              valueFrom:
                configMapKeyRef:
                  key: awss3Uri
                  name: qix-datafiles-configs
            - name: EDGE_AUTH_URI
              valueFrom:
                configMapKeyRef:
                  key: edgeAuthUri
                  name: qix-datafiles-configs
            - name: ENCRYPTION_URI
              valueFrom:
                configMapKeyRef:
                  key: encryptionUri
                  name: qix-datafiles-configs
            - name: FEATURE_FLAGS_CACHEEXPIRATIONINSECONDS
              valueFrom:
                configMapKeyRef:
                  key: featureFlagsCacheexpirationinseconds
                  name: qix-datafiles-configs
            - name: FEATURE_FLAGS_URI
              valueFrom:
                configMapKeyRef:
                  key: featureFlagsUri
                  name: qix-datafiles-configs
            - name: INGRESS_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  key: ingressAuthUrl
                  name: qix-datafiles-configs
            - name: KEYS_URI
              valueFrom:
                configMapKeyRef:
                  key: keysUri
                  name: qix-datafiles-configs
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: logLevel
                  name: qix-datafiles-configs
            - name: NATS_STREAMING_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: natsStreamingClusterId
                  name: qix-datafiles-configs
            - name: NATS_URI
              valueFrom:
                configMapKeyRef:
                  key: natsUri
                  name: qix-datafiles-configs
            - name: OTLP_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  key: otlpAgentPort
                  name: qix-datafiles-configs
            - name: POLICY_DECISIONS_URI
              valueFrom:
                configMapKeyRef:
                  key: policyDecisionsUri
                  name: qix-datafiles-configs
            - name: POLICY_DECISIONS_USEACCESSCONTROLSERVICE
              valueFrom:
                configMapKeyRef:
                  key: policyDecisionsUseaccesscontrolservice
                  name: qix-datafiles-configs
            - name: SPACES_URI
              valueFrom:
                configMapKeyRef:
                  key: spacesUri
                  name: qix-datafiles-configs
            - name: TEMPORARY_CONTENTS_URI
              valueFrom:
                configMapKeyRef:
                  key: temporaryContentsUri
                  name: qix-datafiles-configs
            - name: USERS_URI
              valueFrom:
                configMapKeyRef:
                  key: usersUri
                  name: qix-datafiles-configs
            - name: DISABLE_OTLP
              value: "true"
            - name: JAEGER_DISABLED
              value: "true"
            - name: DATA_DIRECTORY
              value: /qlik/qix-datafiles
            - name: JWTAUTHENTICATION_REQUIRESIGNEDTOKENS
              value: "true"
            - name: NATS_AUTHENABLED
              value: "true"
            - name: TERMINATION_GRACE_PERIOD_SECONDS
              value: "1800"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HTTP_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpProxy
                  name: qliksense-configs
            - name: HTTPS_PROXY
              valueFrom:
                configMapKeyRef:
                  key: httpsProxy
                  name: qliksense-configs
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  key: noProxy
                  name: qliksense-configs
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: mongodbUri
                  name: qliksense-secrets
            - name: MONGODB_URI_FILE
              value: /run/secrets/qlik.com/qliksense/mongodbUri
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redisPassword
                  name: qliksense-secrets
            - name: REDIS_PASSWORD_FILE
              value: /run/secrets/qlik.com/qliksense/redisPassword
          image: ghcr.io/qlik-download/qix-datafiles:4.1.22
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          name: qix-datafiles
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 50051
              name: grpc
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          volumeMounts:
            - mountPath: /run/secrets/qlik.com/qix-datafiles
              name: qix-datafiles-secrets
              readOnly: true
            - mountPath: /qlik/qix-datafiles
              name: qix-datafiles
              readOnly: false
            - mountPath: /tmp
              name: qix-datafiles-tmpdir
              readOnly: false
            - mountPath: /etc/ssl/certs
              name: ca-certificates
            - mountPath: /run/secrets/qlik.com/qliksense
              name: qliksense-secrets
      imagePullSecrets:
        - name: artifactory-docker-secret
      terminationGracePeriodSeconds: 1800
      volumes:
        - name: qix-datafiles-secrets
          secret:
            secretName: qix-datafiles-secrets
        - emptyDir: {}
          name: qix-datafiles-tmpdir
        - name: qix-datafiles
          persistentVolumeClaim:
            claimName: qix-datafiles
        - name: ca-certificates
          persistentVolumeClaim:
            claimName: ca-certificates
        - name: qliksense-secrets
          secret:
            secretName: qliksense-secrets
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles
  namespace: default
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qix-datafiles
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://edge-auth.$(NAMESPACE).svc.cluster.local:8080/v1/auth
    nginx.ingress.kubernetes.io/client-body-buffer-size: 10m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite (?i)/api/v1/(.*) /v1/$1 break;
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.org/client-max-body-size: 500m
  labels:
    app: qix-datafiles
    app.kubernetes.io/component: qix-datafiles
    app.kubernetes.io/instance: qix-datafiles
    app.kubernetes.io/name: qix-datafiles
    app.kubernetes.io/version: 4.1.22
    chart: qix-datafiles-4.1.22
    domain: data-connectors
    heritage: Helm
    release: qix-datafiles
  name: qix-datafiles
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - backend:
              service:
                name: qix-datafiles
                port:
                  number: 8080
            path: /api/v1/qix-datafiles
            pathType: ImplementationSpecific
          - backend:
              service:
                name: qix-datafiles
                port:
                  number: 8080
            path: /api/v1/data-files
            pathType: ImplementationSpecific
