apiVersion: v2
name: kube-prometheus-stack
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
- name: kube-prometheus-stack
  version: 34.10.0
  repository: https://prometheus-community.github.io/helm-charts
